### PR TITLE
adding npm files filter

### PR DESCRIPTION
**Pull request by TrySound**
for smaller package

### CODE REVIEW

**Comment by thlorenz** [comment]
I like tests and examples to be included so people can read them even when offline.
They are really not huge. Did you actually measure the difference? I bet it's minute.

**Comment by TrySound** [comment]
@thlorenz I'm just trying to reduce size of browserify. But okay :)

**Comment by thlorenz** [comment]
I didn't say no yet ;)
Just please do an `npm pack` with your change and without and then compare what size we'd actually gain.
If it's worth it I'm willing to sacrifice the above reasons for not slimming the package especially since lots of people will download this with browserify.

**Comment by TrySound** [comment]
It's smallest size. Will search more heavy packages.

**Pull request closed without merging**
