### PR TITLE
update source-map, tap and nave

### PR DESCRIPTION
**Pull request by shinnn**

### CODE REVIEW

**Comment by shinnn** [comment]
@thlorenz Could you enable `Build Pull Requests` option on Travis CI? It's vey useful for contributors.

image

**Comment by thlorenz** [comment]
What does this PR improve?

> Could you enable Build Pull Requests option on Travis CI?

I thought it was enabled by default and it actually is on:

screen shot 2015-02-26 at 1 36 47 pm

**Comment by shinnn** [comment]
> What does this PR improve?

It includes performance improvement. https://github.com/mozilla/source-map/pull/159

> I thought it was enabled by default and it actually is on

Oh, that seems to be enabled correctly. I can't see why Travis CI doesn't build our pull requests on this project. https://travis-ci.org/thlorenz/inline-source-map/pull_requests

**Comment by thlorenz** [comment]
Ok then please only update the source-map dependency.

**Comment by thlorenz** [comment]
Actually never mind - I'll pull this in as is when I get a chance.
Thanks.

**Comment by thlorenz** [comment]
Thanks, published as 0.5.

**Comment by shinnn** [comment]
Thanks.

**Pull request closed without merging**
