### PR TITLE
update source-map to ~0.5.3

### PR DESCRIPTION
**Pull request by zertosh**
related to https://github.com/thlorenz/combine-source-map/pull/20

### CODE REVIEW

**Comment by ashaffer** [comment]
@thlorenz Any updates on this? There is a huge perf boost to source-map PR'd by @zertosh. It'd be really nice to have in browserify, and I don't think the API has changed much.

**Comment by thlorenz** [comment]
@zertosh and @ashaffer made you both collaborators here and on combine-source-map.

@zertosh added you as collaborator on both npm packages as well.

Please either of you merge to master following [this guide](https://gist.github.com/thlorenz/f7df0daf13c6f6c1fa84).
I or @zertosh will then version and publish to npm.

Thanks for your help .. I myself don't have the bandwidth to take care of this in a timely manner.

**Comment by zertosh** [comment]
Thanks @thlorenz!

**Comment by ashaffer** [comment]
Thx @thlorenz. You wanna take care of this since it's your PR @zertosh? I'm happy to do it if you'd like, but I figure you are more familiar with it :).

**Comment by zertosh** [comment]
@thlorenz now that GitHub supports [commit squashing](https://github.com/blog/2141-squash-your-commits), you may want to update the note in the Collaborator gist about merge commits. Also, only the owner can disable merge commits in favor of squash merging.

**Comment by zertosh** [comment]
Published as inline-source-map@0.6.2

**Pull request merged**
