### PR TITLE
change `charset:` to `charset=`

### PR DESCRIPTION
**Pull request by shootaroo**
Supported the Google Chrome.

See https://github.com/thlorenz/inline-source-map/issues/6#issuecomment-119096882

### CODE REVIEW

**Comment by thlorenz** [comment]
Could you please point me to the specification that says that it should be `=` instead of `:`?
I don't want to change this for chrome and then find out it breaks in Firefox or so.

**Comment by shootaroo** [comment]
Firefox supports both. Chrome support `=` only.

## charset:utf-8
screen shot 2015-07-17 at 0 54 32
### Chrome
screen shot 2015-07-17 at 0 54 52
### Firefox
screen shot 2015-07-17 at 1 00 19
### IE11
screen shot 2015-07-17 at 1 44 25

## charset=utf-8
screen shot 2015-07-17 at 0 55 13
### Chrome
screen shot 2015-07-17 at 0 55 31
### Firefox
screen shot 2015-07-17 at 1 01 30
### IE11
screen shot 2015-07-17 at 1 44 45

**Comment by thlorenz** [comment]
Thanks for digging in, but is there a spec somewhere we can reference for the future as well?
Or at least links to the source code that implements this (obviously won't be available for IE)?

**Comment by thlorenz** [comment]
Code changes LGTM, so you can definitely merge into master (made you a collab).
I'll publish as a new minor version once that's done.

I'd just like to have more references we could link in the commit message and if people ask about it in issues.

**Comment by shootaroo** [comment]
I put a link of [RFC 2397](https://tools.ietf.org/html/rfc2397) in the commit message.

Thank you!

**Comment by thlorenz** [comment]
Thanks, I fixed master (hate merge commit noise)
It'll conflict with yours now until you do `git reset HEAD^^ --hard && git pull --rebase`, please only do forward merges in the future.

Published as 0.6. Again thanks for the help.

**Pull request merged**
